### ISSUE TITLE
Zaključevanje s projektom

### ISSUE THREAD

**Issue by tiakrofel** [tiakrofel/APPR-2020-21#1]
Pozdravljeni,
mislim, da sem s svojim projektom zaključila in prosila bi še za zadnji pregled pred oddajo.

**Comment by jaanos** [comment]
Nimam pripomb, tako da bom dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjala, mi javi, da posodobim povezavo.
